CREATE TABLE `aims_record_set` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NOT NULL,
  `Label` VARCHAR(50) DEFAULT NULL,
  `BaseQuery` VARCHAR(50) DEFAULT NULL,
  `SortOrder` INT DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
