name: Sonar Scans

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  changes:
    name: Check for Changed Services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            PHIASPACE.API: PHIASPACE.API/**
            PHIASPACE.CORE: PHIASPACE.CORE/**
            PHIASPACE.INCIDENCE: PHIASPACE.INCIDENCE/**
            PHIASPACE.INTERFACE: PHIASPACE.INTERFACE/**
            PHIASPACE.LINKAGE: PHIASPACE.LINKAGE/**
            PHIASPACE.MAPPINGLISTING: PHIASPACE.MAPPINGLISTING/**
            PHIASPACE.RTDMS: PHIASPACE.RTDMS/**
            PHIASPACE.SAMPLEMODULE: PHIASPACE.SAMPLEMODULE/**
            PHIASPACE.TICKETING: PHIASPACE.TICKETING/**
            PHIASPACE.TRAINING: PHIASPACE.TRAINING/**
    outputs:
      packages: ${{ steps.filter.outputs.changes }}

  build_and_analyze:
    name: Build And Analyze Apps
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' }}
    needs: changes
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Install dependencies
        run: dotnet restore

      - name: Install dotnet-sonarscanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add dotnet tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: Run Sonar Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"201-ciheb_studdyspacesonar" \
            /o:"201-ciheb" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.scanner.skipJreProvisioning=true \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
