// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHIASPACE.TRAINING.DAL.Model;

#nullable disable

namespace PHIASPACE.TRAINING.Migrations
{
    [DbContext(typeof(PhiaSpaceTrainingContext))]
    [Migration("20221012014659_models")]
    partial class models
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblCertificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"), 1L, 1);

                    b.Property<string>("CertStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonIdentificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CertificateId");

                    b.HasIndex("CourseId");

                    b.HasIndex("PersonIdentificationCode");

                    b.HasIndex("TrainingId");

                    b.ToTable("Tbl_Certificate");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblCourse", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                    b.Property<int?>("CertificateType")
                        .HasColumnType("int");

                    b.Property<int?>("CmeUnits")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<double?>("PassScore")
                        .HasColumnType("float");

                    b.Property<string>("ThematicArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValidityPeriodMonths")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.ToTable("Tbl_Course");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblDistrict", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Tbl_District");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblFacility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"), 1L, 1);

                    b.Property<int>("ClassificationId")
                        .HasColumnType("int");

                    b.Property<string>("DistrictId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId1")
                        .HasColumnType("int");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ProvinceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId1")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UsClassificationId")
                        .HasColumnType("int");

                    b.Property<string>("UsCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacilityId");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("DistrictId1");

                    b.HasIndex("LevelId");

                    b.HasIndex("ProvinceId1");

                    b.ToTable("Tbl_Facility");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblFacilityClassification", b =>
                {
                    b.Property<int>("ClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassificationId"), 1L, 1);

                    b.Property<string>("ClassificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassificationId");

                    b.ToTable("Tbl_FacilityClassification");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblFacilityLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"), 1L, 1);

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LevelId");

                    b.ToTable("Tbl_FacilityLevel");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblFacilityTransfers", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonIdentificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TransferIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransferId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("PersonIdentificationCode");

                    b.ToTable("Tbl_FacilityTransfers");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblLookup", b =>
                {
                    b.Property<int>("LookupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LookupId"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("LookupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LookupId");

                    b.ToTable("Tbl_Lookup");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblPersons", b =>
                {
                    b.Property<string>("IdentificationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("TblFacilityFacilityId")
                        .HasColumnType("int");

                    b.Property<int?>("Title")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdentificationCode");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("TblFacilityFacilityId");

                    b.ToTable("Tbl_Persons");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblProfession", b =>
                {
                    b.Property<int>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessionId"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfessionId");

                    b.ToTable("Tbl_Profession");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblProvince", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"), 1L, 1);

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Tbl_Province");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTraining", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"), 1L, 1);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpectedParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statusmessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainingstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("TrainingId");

                    b.HasIndex("CourseId");

                    b.HasIndex("VenueId");

                    b.ToTable("Tbl_Training");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTrainingFacilitator", b =>
                {
                    b.Property<int>("FacilitatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilitatorId"), 1L, 1);

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonIdentificationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FacilitatorId");

                    b.HasIndex("PersonIdentificationCode");

                    b.HasIndex("TrainingId");

                    b.ToTable("Tbl_TrainingFacilitator");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTrainingParticipant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"), 1L, 1);

                    b.Property<int?>("CompletionStatus")
                        .HasColumnType("int");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<double?>("FinalScore")
                        .HasColumnType("float");

                    b.Property<string>("IdentificationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonIdentificationCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("PostTestScore")
                        .HasColumnType("float");

                    b.Property<double?>("PreTestScore")
                        .HasColumnType("float");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ParticipantId");

                    b.HasIndex("PersonIdentificationCode");

                    b.HasIndex("TrainingId");

                    b.ToTable("Tbl_TrainingParticipant");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTrainingVenue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Deleted")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Tbl_Venue");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblCertificate", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblCourse", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblPersons", "Person")
                        .WithMany()
                        .HasForeignKey("PersonIdentificationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblTraining", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Person");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblDistrict", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblProvince", "Province")
                        .WithMany("TblDistricts")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblFacility", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblFacilityClassification", "Classification")
                        .WithMany()
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblDistrict", "District")
                        .WithMany("Facilities")
                        .HasForeignKey("DistrictId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblFacilityLevel", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId");

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblProvince", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("District");

                    b.Navigation("Level");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblFacilityTransfers", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblFacility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblPersons", "Person")
                        .WithMany()
                        .HasForeignKey("PersonIdentificationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblPersons", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblDistrict", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblProfession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId");

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblProvince", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblFacility", "TblFacility")
                        .WithMany()
                        .HasForeignKey("TblFacilityFacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Profession");

                    b.Navigation("Province");

                    b.Navigation("TblFacility");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTraining", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblCourse", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblTrainingVenue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId");

                    b.Navigation("Course");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTrainingFacilitator", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblPersons", "Person")
                        .WithMany()
                        .HasForeignKey("PersonIdentificationCode");

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblTraining", "Training")
                        .WithMany("TrainingFacilitators")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTrainingParticipant", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblPersons", "Person")
                        .WithMany()
                        .HasForeignKey("PersonIdentificationCode");

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblTraining", "Training")
                        .WithMany("TrainingParticipants")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTrainingVenue", b =>
                {
                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblDistrict", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("PHIASPACE.TRAINING.DAL.Model.Db.TblProvince", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblDistrict", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblProvince", b =>
                {
                    b.Navigation("TblDistricts");
                });

            modelBuilder.Entity("PHIASPACE.TRAINING.DAL.Model.Db.TblTraining", b =>
                {
                    b.Navigation("TrainingFacilitators");

                    b.Navigation("TrainingParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
